name: Hola Mundo

on: 
 push: 
    branches:
      - master
 workflow_dispatch:

jobs:
    hola:
      runs-on: ubuntu-latest
      steps:
        - name: Saludar
          run: echo "Hola Mundo"
        - name: Descargar Codigo
          uses: actions/checkout@v4
        - name: En que carpeta estoy
          run: pwd
        - name : Listar Archivos
          run: ls -la 
        - name: Instalar Node
          uses: actions/setup-node@v3
        
